### ISSUE TITLE
How to open menu?

### ISSUE THREAD

**Issue by SagMeinenNamen** [TobyAdd/GDH-Overlay#5]
Is there a key to open the menu? When yes, which one? It does not appear to work for me, help would be nice.

**Comment by TobyAdd** [comment]
Hello, the key is tab. If it didnt work, theb install visual c++ redistributable (2017-2019)

**Comment by TobyAdd** [comment]
i recommend to install all https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/?amp

**Comment by SagMeinenNamen** [comment]
Thank you, it works now!

**Comment by TobyAdd** [comment]
np
