### ISSUE TITLE
seetting

### ISSUE THREAD

**Issue by l0zthrental** [TobyAdd/GDH-Overlay#6]
![Ảnh chụp màn hình 2022-06-07 175637](https://user-images.githubusercontent.com/95627666/172363272-b20c8616-5468-4f77-a0a5-a97b14c025fa.png)

**Comment by TobyAdd** [comment]
How i can help you?

**Comment by oneparsec** [comment]
> How i can help you?

He's talking about grammar mistake

**Comment by TobyAdd** [comment]
Oh really, thanks l0zthrental for noticing mistake, it will be fixed later

**Comment by TobyAdd** [comment]
fixed
