### ISSUE TITLE
В дуале CPS counter считает по два клика за раз

### ISSUE THREAD

**Issue by thisisignitedoreo** [TobyAdd/GDH-Overlay#8]
![CPS-counter-bug](https://user-images.githubusercontent.com/97063750/188308650-3890613d-d0d0-433b-ae2f-c0c55860a335.gif)

**Comment by TobyAdd** [comment]
Сегодня вечером пофикшу, спасибо за находку багов

**Comment by TobyAdd** [comment]
Пофиксил
